---
preBuildScript: "sed -i \"s/'mavenPublish': '0.8.0'/'mavenPublish': '0.9.0'/\" wire-library/dependencies.gradle"
additionalArgs:
  - "-p"
  - "wire-library"
  - "-Dkjs=false"
  - "-Dknative=false"
  - "-Pswift=false"
