---
preBuildScript: |
  export JDK_18="$JAVA_HOME"
  find . -name build.gradle -exec sed -i /dokka.gradle.kts/d {} \;
enforceVersion: true
additionalArgs:
  - "-Pdisable_native_targets=true"
repositories:
  - "all"
  - "jetbrains-kotlinx"
