---
enforceVersion: true
additionalArgs:
  - "-Pnative.deploy=disabled"
  - "-x"
  - ":kotlinx-serialization-cbor:dokkaHtml"
  - "-x"
  - ":kotlinx-serialization-core:dokkaHtml"
  - "-x"
  - ":kotlinx-serialization-json:dokkaHtml"
  - "-x"
  - ":kotlinx-serialization-properties:dokkaHtml"
  - "-x"
  - ":kotlinx-serialization-hocon:dokkaHtml"
  - "-x"
  - ":kotlinx-serialization-protobuf:dokkaHtml"
  - "-x"
  - ":dokkaHtmlMultiModule"
  - "-x"
  - ":knitCheck"
