---
preBuildScript: "sed -i -e \"s/'mavenPublish': '0.8.0'/'mavenPublish': '0.10.0'/\" wire-library/dependencies.gradle"
enforceVersion: true
additionalArgs:
  - "-p"
  - "wire-library"
  - "-Dkjs=false"
  - "-Dknative=false"
  - "-Pswift=false"
  - "-PRELEASE_SIGNING_ENABLED=false"
  - "uploadArchives"
