---
ignoredArtifacts:
  - "vertx-web-templ-jade"
  - "vertx-web-templ-thymeleaf"
  - "vertx-web-templ-rythm"
  - "vertx-web-templ-mvel"
  - "vertx-web-templ-pebble"
  - "vertx-web-templ-rocker"
  - "vertx-web-templ-httl"
  - "vertx-web-templ-jte"
  - "vertx-web-templ-freemarker"
  - "vertx-web-templ-handlebars"
