---
preBuildScript: |
    sed -i "s/^dependencies {$/dependencies {\n    constraints { implementation(group = 'org.ajoberstar.grgit', name = 'grgit-gradle', version = '4.0.0') }/" buildSrc/build.gradle.kts
additionalArgs:
  - "-x"
  - "signArchives"
