---
additionalArgs:
  - "-DskipDocs=true"
  - "-Dno-test-modules"
ignoredArtifacts:
  - "quarkus-cli"
  - "quarkus-maven-plugin"
  - "quarkus-grpc-protoc-plugin"
  - "quarkus-bootstrap-gradle-resolver"